# www.fanshopping.com.tw
#database.driver=com.mysql.cj.jdbc.Driver
#database.url=jdbc:mysql://localhost:3306/www.fanshopping.com.tw?useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&connectTimeout=0&socketTimeout=0&autoReconnect=true
#database.user=root
#database.password=fanshopping168861
#hibernate.show_sql=true
#hibernate.format_sql=true

# 1.87 windows
#database.driver=com.mysql.cj.jdbc.Driver
#database.url=jdbc:mysql://210.61.64.59:13306/fanshopping20170323?useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&connectTimeout=0&socketTimeout=0&autoReconnect=true
#database.user=root
#database.password=BF109g10
#hibernate.show_sql=true
#hibernate.format_sql=true

#Localhost
database.driver=com.mysql.cj.jdbc.Driver
database.url=jdbc:mysql://localhost:3306/fanshopping?useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&connectTimeout=0&socketTimeout=0&autoReconnect=true
database.user=root
database.password=3I7UWT9D#
hibernate.show_sql=true
hibernate.format_sql=true

#Linux
#database.driver=com.mysql.cj.jdbc.Driver
#database.url=jdbc:mysql://192.168.1.187:3306/fanshopping_backup_20170911?useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&connectTimeout=0&socketTimeout=0&autoReconnect=true
#database.user=dbadmin
#database.password=asdfghjklpoiuytrewq
#hibernate.show_sql=true
#hibernate.format_sql=true